#!/bin/bash

#Ask the user for inputs (DB name, table name, user name, user password)

read -p "Enter user name: " #user_name
read -p "Enter user Password: " #user_passwd  --> hide the password

read -p "Enter database name: " #DB_name
read -p "Enter table name: " #DB_table

#let the user confirm before delete

echo "You want to delete table: #$table_name" 
read -p "Continue? (y/n): " Confirm

if ['$Confirm'!= "y"];
then
    echo "keep the script" #check this part again
    exit 1
fi


#clear table content/data

sed -i '2,$d' "#$table_name"

echo "The table content of #$table_name is now deleted! "
